### ISSUE TITLE
Most recent commit 5218b6a (adding gif support) broke a few things.

### ISSUE THREAD

**Issue by avolation** [avinayak/redditv#1]
1. Links in bottom left no longer work. Can't open reddit comments link. Can't open screen to show keyboard shortcuts or subreddit list.
2. Once a gif starts playing you can no longer switch between subs (Up and down arrow) but you can still switch to next and previous inside the current sub.

**Comment by avinayak** [comment]
There seems to be a slight problem with GIF Playback. I've rolled back to the older version for now. Will fix this soon

**Comment by avinayak** [comment]
BTW gif subreddits can still be watched using /redditv/#<gif subreddit name>

**Comment by avinayak** [comment]
I've fixed it( I hope). will run for a few days. If working, this issue will be closed

**Comment by avolation** [comment]
Works perfect on my end now in Chrome/FF/Edge. Great work!

**Comment by avinayak** [comment]
Awesome :smile:
